#!/bin/bash

# Sync all the remote committed changes

cd system/core;
# init: Allow load of lpm.rc by parsing a cmdline argument
git fetch https://gerrit.omnirom.org/android_system_core refs/changes/67/3367/3 && git cherry-pick FETCH_HEAD;
cd ..; cd ..;
